import { test } from 'node:test';
import assert from 'node:assert/strict';
import { makeSyntheticCohort,filterCohort,aggregateCount,groupCases,sharedFactors,relatedCases,regions,syntheticCaseTotal } from '../src/cohort.ts';
const all={onset:'Any',age:'Any',occupation:'Any',exposure:'Any'};
test('research aggregation excludes non-consenting records',()=>{const rows=makeSyntheticCohort();const found=filterCohort(rows,all);assert.equal(rows.length,syntheticCaseTotal);assert.ok(found.length<rows.length);assert.ok(found.every(r=>r.consent));assert.equal(found.length,rows.filter(r=>r.consent).length)});
test('combined filters constrain every dimension',()=>{const filters={onset:'Limb',age:'Under 60',occupation:'Automotive',exposure:'Solvents'};const found=filterCohort(makeSyntheticCohort(),filters);assert.ok(found.length>0);assert.ok(found.every(r=>r.age<60&&r.onset==='Limb'&&r.occupation==='Automotive'&&r.exposure==='Solvents'&&r.consent))});
test('small cohorts suppress aggregate counts',()=>{const rows=makeSyntheticCohort();assert.equal(aggregateCount(rows.slice(0,9)),null);assert.equal(aggregateCount(rows.slice(0,10)),10)});
test('synthetic dataset is deterministic and has no patient identifiers',()=>{const rows=makeSyntheticCohort();assert.deepEqual(rows,makeSyntheticCohort());assert.ok(rows.every(r=>!('name' in r)&&!('email' in r)&&!('id' in r)))});

test('geographic and diagnosis-period filters constrain the synthetic cases',()=>{const found=filterCohort(makeSyntheticCohort(),{...all,state:'NSW',region:'hunter',period:'2019–2022'});assert.ok(found.length>=10);assert.ok(found.every(r=>r.consent&&r.state==='NSW'&&r.region==='hunter'&&r.diagnosisYear>=2019&&r.diagnosisYear<=2022))});
test('every generated location refers to a known region and state',()=>{for(const row of makeSyntheticCohort()){assert.equal(row.state,regions.find(r=>r.id===row.region)?.state);assert.ok(regions.some(r=>r.id===row.priorRegion));assert.ok(row.diagnosisYear>=2015&&row.diagnosisYear<=2026)}});
test('aggregate groups respect consent and suppress small cells',()=>{const rows=makeSyntheticCohort();const groups=groupCases(rows,'region');assert.equal(groups.reduce((n,g)=>n+(g.count??0),0),rows.filter(r=>r.consent).length);const sample=rows.filter(r=>r.consent).slice(0,9);assert.ok(groupCases(sample,'region').every(g=>g.count===null));assert.deepEqual(groupCases(rows.filter(r=>!r.consent),'state'),[])});
test('connections reflect shared fields and exclude non-consenting cases',()=>{const rows=makeSyntheticCohort(),focus=rows.find(r=>r.consent);const links=relatedCases(rows,focus);assert.ok(links.length>0);for(const link of links){assert.ok(link.row.consent);assert.notEqual(link.row,focus);assert.deepEqual(link.shared,sharedFactors(focus,link.row));assert.ok(link.shared.length>0)}assert.deepEqual(relatedCases(rows,rows.find(r=>!r.consent)),[]);assert.deepEqual(relatedCases(rows.filter(r=>r.consent).slice(0,9),focus),[])});
